name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - name: Skip build
        run: echo 'No build required'
